feeds:
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-CA&gl=CA&ceid=CA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-US&gl=US&ceid=US:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-IN&gl=IN&ceid=IN:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-AU&gl=AU&ceid=AU:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-GB&gl=GB&ceid=GB:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-NZ&gl=NZ&ceid=NZ:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-ZA&gl=ZA&ceid=ZA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-CA&gl=CA&ceid=CA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-US&gl=US&ceid=US:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-IN&gl=IN&ceid=IN:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-AU&gl=AU&ceid=AU:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-GB&gl=GB&ceid=GB:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-NZ&gl=NZ&ceid=NZ:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-ZA&gl=ZA&ceid=ZA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+attack&scoring=n&hl=en-AE&gl=AE&ceid=AE:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+breach&scoring=n&hl=en-AE&gl=AE&ceid=AE:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-CA&gl=CA&ceid=CA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-US&gl=US&ceid=US:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-IN&gl=IN&ceid=IN:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-AU&gl=AU&ceid=AU:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-GB&gl=GB&ceid=GB:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-NZ&gl=NZ&ceid=NZ:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-ZA&gl=ZA&ceid=ZA:en
- category: google_news
  region: EN
  url: https://news.google.com/rss/search?tbm=nws&q=when:12h+cyber+incident&scoring=n&hl=en-AE&gl=AE&ceid=AE:en
- category: intel_blog
  region: Global
