- url: https://www.bing.com/news/search?q=cyber+attack&format=rss
  category: Bing
  region: Global

- url: https://www.bing.com/news/search?q=cybersecurity+hacks&format=rss
  category: Bing
  region: Global
