- url: https://feeds.feedburner.com/TheHackersNews
  category: Native
  region: Global

- url: https://www.securityweek.com/feed
  category: Native
  region: US

- url: https://www.darkreading.com/rss.xml
  category: Native
  region: Global
