name: Manual Feed Validator

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  validate-feeds:
    runs-on: ubuntu-latest
    name: Validate All RSS Feeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run Feed Validator
        run: python scripts/validate_feeds.py
