name: Manual Feed Validator

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: 'Path to feed config file (optional)'
        required: false
        default: 'config/threatdigest.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate RSS Feed List
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml requests

      - name: Run Feed Validator
        run: |
          python scripts/validate_feeds.py ${{ github.event.inputs.config_file }}
