name: Validate RSS Feeds

on:
  push:
    paths:
      - 'config/*.yaml'
      - 'scripts/validate_feeds.py'
  pull_request:
    paths:
      - 'config/*.yaml'
      - 'scripts/validate_feeds.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml feedparser

      - name: Run feed validator
        run: python scripts/validate_feeds.py
